# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
import re  # noqa: F401,E501
from swagger_server import util


class CreateDataResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data_id: str=None, vehicle_id: str=None, data_hora: datetime=None):  # noqa: E501
        """CreateDataResponse - a model defined in Swagger

        :param data_id: The data_id of this CreateDataResponse.  # noqa: E501
        :type data_id: str
        :param vehicle_id: The vehicle_id of this CreateDataResponse.  # noqa: E501
        :type vehicle_id: str
        :param data_hora: The data_hora of this CreateDataResponse.  # noqa: E501
        :type data_hora: datetime
        """
        self.swagger_types = {
            'data_id': str,
            'vehicle_id': str,
            'data_hora': datetime
        }

        self.attribute_map = {
            'data_id': 'data_id',
            'vehicle_id': 'vehicle_id',
            'data_hora': 'data_hora'
        }
        self._data_id = data_id
        self._vehicle_id = vehicle_id
        self._data_hora = data_hora

    @classmethod
    def from_dict(cls, dikt) -> 'CreateDataResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateDataResponse of this CreateDataResponse.  # noqa: E501
        :rtype: CreateDataResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data_id(self) -> str:
        """Gets the data_id of this CreateDataResponse.


        :return: The data_id of this CreateDataResponse.
        :rtype: str
        """
        return self._data_id

    @data_id.setter
    def data_id(self, data_id: str):
        """Sets the data_id of this CreateDataResponse.


        :param data_id: The data_id of this CreateDataResponse.
        :type data_id: str
        """

        self._data_id = data_id

    @property
    def vehicle_id(self) -> str:
        """Gets the vehicle_id of this CreateDataResponse.


        :return: The vehicle_id of this CreateDataResponse.
        :rtype: str
        """
        return self._vehicle_id

    @vehicle_id.setter
    def vehicle_id(self, vehicle_id: str):
        """Sets the vehicle_id of this CreateDataResponse.


        :param vehicle_id: The vehicle_id of this CreateDataResponse.
        :type vehicle_id: str
        """
        if vehicle_id is None:
            raise ValueError("Invalid value for `vehicle_id`, must not be `None`")  # noqa: E501

        self._vehicle_id = vehicle_id

    @property
    def data_hora(self) -> datetime:
        """Gets the data_hora of this CreateDataResponse.

        Data hora  # noqa: E501

        :return: The data_hora of this CreateDataResponse.
        :rtype: datetime
        """
        return self._data_hora

    @data_hora.setter
    def data_hora(self, data_hora: datetime):
        """Sets the data_hora of this CreateDataResponse.

        Data hora  # noqa: E501

        :param data_hora: The data_hora of this CreateDataResponse.
        :type data_hora: datetime
        """
        if data_hora is None:
            raise ValueError("Invalid value for `data_hora`, must not be `None`")  # noqa: E501

        self._data_hora = data_hora
