"""making changes

Revision ID: 071c445a53b8
Revises: a8109b912eff
Create Date: 2023-03-05 17:58:18.660233

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = '071c445a53b8'
down_revision = 'a8109b912eff'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
