"""making changes

Revision ID: 079b42fad5c8
Revises: e4cbfec3b6b5
Create Date: 2023-03-05 17:52:06.886104

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = '079b42fad5c8'
down_revision = 'e4cbfec3b6b5'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
