"""making changes

Revision ID: 12b5541ba773
Revises: 079b42fad5c8
Create Date: 2023-03-05 17:52:18.328625

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = '12b5541ba773'
down_revision = '079b42fad5c8'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
