"""making changes

Revision ID: 1c685774e2e5
Revises: 52fcb7c38977
Create Date: 2023-03-05 18:12:26.797871

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = '1c685774e2e5'
down_revision = '52fcb7c38977'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
