"""making changes

Revision ID: 1d6d1bc24c7a
Revises: eca466618037
Create Date: 2023-03-05 17:46:13.433509

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = '1d6d1bc24c7a'
down_revision = 'eca466618037'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
