"""making changes

Revision ID: 33d2ea6d89ac
Revises: fc850c1b62bf
Create Date: 2023-03-05 17:51:20.393549

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = '33d2ea6d89ac'
down_revision = 'fc850c1b62bf'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
