"""making changes

Revision ID: 4e95e2191d52
Revises: 071c445a53b8
Create Date: 2023-03-05 17:58:39.608047

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = '4e95e2191d52'
down_revision = '071c445a53b8'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
