"""making changes

Revision ID: 51d082dfa1f7
Revises: a829405fc8df
Create Date: 2023-03-05 17:45:58.429652

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = '51d082dfa1f7'
down_revision = 'a829405fc8df'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
