"""making changes

Revision ID: 52fcb7c38977
Revises: e8e09ebdd6cf
Create Date: 2023-03-05 18:04:39.446326

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = '52fcb7c38977'
down_revision = 'e8e09ebdd6cf'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
