"""making changes

Revision ID: 53675df72009
Revises: a6bbd576d4e0
Create Date: 2023-03-05 18:13:34.198813

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = '53675df72009'
down_revision = 'a6bbd576d4e0'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
