"""making changes

Revision ID: 581264bc6614
Revises: 
Create Date: 2023-03-05 10:56:15.966577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581264bc6614'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
