"""making changes

Revision ID: 7207f8592f22
Revises: 90972ced81a3
Create Date: 2023-03-05 18:15:06.139395

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = '7207f8592f22'
down_revision = '90972ced81a3'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
