"""making changes

Revision ID: 79537b5b6266
Revises: ae68174ce075
Create Date: 2023-03-05 17:52:48.302243

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = '79537b5b6266'
down_revision = 'ae68174ce075'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
