"""making changes

Revision ID: 7b827fd698d6
Revises: ee185bb19fd6
Create Date: 2023-03-05 18:04:22.189394

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = '7b827fd698d6'
down_revision = 'ee185bb19fd6'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
