"""making changes

Revision ID: 7c82f82872be
Revises: bec371c2fc44
Create Date: 2023-03-05 18:14:04.291386

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = '7c82f82872be'
down_revision = 'bec371c2fc44'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
