"""making changes

Revision ID: 7effe1a0f2b0
Revises: 
Create Date: 2023-03-05 17:42:16.399155

"""
from alembic import op
import sqlalchemy as sa
import config
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7effe1a0f2b0'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('data_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('vehicle_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('data_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    # ### end Alembic commands ###
