"""making changes

Revision ID: 90972ced81a3
Revises: 7c82f82872be
Create Date: 2023-03-05 18:14:50.936111

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = '90972ced81a3'
down_revision = '7c82f82872be'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
