"""making changes

Revision ID: 92a303de8935
Revises: bd9f5b6159da
Create Date: 2023-03-05 17:44:50.681590

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = '92a303de8935'
down_revision = 'bd9f5b6159da'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
