"""making changes

Revision ID: 92b21baa2ff3
Revises: 581264bc6614
Create Date: 2023-03-05 10:56:17.688964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b21baa2ff3'
down_revision = '581264bc6614'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
