"""making changes

Revision ID: 9a181b8895f8
Revises: 1d6d1bc24c7a
Create Date: 2023-03-05 17:47:57.224096

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = '9a181b8895f8'
down_revision = '1d6d1bc24c7a'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
