"""making changes

Revision ID: a3515b516874
Revises: 7effe1a0f2b0
Create Date: 2023-03-05 17:42:18.114351

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = 'a3515b516874'
down_revision = '7effe1a0f2b0'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
