"""making changes

Revision ID: a6bbd576d4e0
Revises: 1c685774e2e5
Create Date: 2023-03-05 18:12:41.708646

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = 'a6bbd576d4e0'
down_revision = '1c685774e2e5'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
