"""making changes

Revision ID: a8109b912eff
Revises: e3c7c2dcc200
Create Date: 2023-03-05 17:57:18.180997

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = 'a8109b912eff'
down_revision = 'e3c7c2dcc200'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
