"""making changes

Revision ID: a829405fc8df
Revises: 92a303de8935
Create Date: 2023-03-05 17:45:49.114027

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = 'a829405fc8df'
down_revision = '92a303de8935'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
