"""making changes

Revision ID: ae68174ce075
Revises: 12b5541ba773
Create Date: 2023-03-05 17:52:34.521369

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = 'ae68174ce075'
down_revision = '12b5541ba773'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
