"""making changes

Revision ID: b2069a2d4960
Revises: 79537b5b6266
Create Date: 2023-03-05 17:53:03.367644

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = 'b2069a2d4960'
down_revision = '79537b5b6266'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
