"""making changes

Revision ID: bd9f5b6159da
Revises: a3515b516874
Create Date: 2023-03-05 17:42:58.829852

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = 'bd9f5b6159da'
down_revision = 'a3515b516874'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
