"""making changes

Revision ID: bec371c2fc44
Revises: 53675df72009
Create Date: 2023-03-05 18:13:51.599990

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = 'bec371c2fc44'
down_revision = '53675df72009'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
