"""making changes

Revision ID: d256f6a025e9
Revises: 4e95e2191d52
Create Date: 2023-03-05 18:03:40.503246

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = 'd256f6a025e9'
down_revision = '4e95e2191d52'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
