"""making changes

Revision ID: e3c7c2dcc200
Revises: b2069a2d4960
Create Date: 2023-03-05 17:56:47.847908

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = 'e3c7c2dcc200'
down_revision = 'b2069a2d4960'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
