"""making changes

Revision ID: e4cbfec3b6b5
Revises: 33d2ea6d89ac
Create Date: 2023-03-05 17:51:26.227154

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = 'e4cbfec3b6b5'
down_revision = '33d2ea6d89ac'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
