"""making changes

Revision ID: e8e09ebdd6cf
Revises: 7b827fd698d6
Create Date: 2023-03-05 18:04:27.892385

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = 'e8e09ebdd6cf'
down_revision = '7b827fd698d6'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
