"""making changes

Revision ID: eca466618037
Revises: 51d082dfa1f7
Create Date: 2023-03-05 17:46:04.281836

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = 'eca466618037'
down_revision = '51d082dfa1f7'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
