"""making changes

Revision ID: ee185bb19fd6
Revises: d256f6a025e9
Create Date: 2023-03-05 18:04:01.300740

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = 'ee185bb19fd6'
down_revision = 'd256f6a025e9'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
