"""making changes

Revision ID: f5031275f937
Revises: 7207f8592f22
Create Date: 2023-03-05 18:15:16.439589

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = 'f5031275f937'
down_revision = '7207f8592f22'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
