"""making changes

Revision ID: fc850c1b62bf
Revises: 9a181b8895f8
Create Date: 2023-03-05 17:48:22.967389

"""
from alembic import op
import sqlalchemy as sa
import config


# revision identifiers, used by Alembic.
revision = 'fc850c1b62bf'
down_revision = '9a181b8895f8'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
